### ISSUE TITLE
Tests fail with syntax error

### ISSUE THREAD

**Issue by patrick-lenggenhager** [patrick-lenggenhager/HyperCells#5]
**Describe the bug**
It seems that certain line breaks in the expected output in GAP test files cannot be handled by the testing suite, e.g., the first line of
```gap
 1, <identity ...> ], [ 25, 1, 1, <identity ...> ], [ 41, 25, 1, <identity ...\
> ], [ 4, 41, 2, <identity ...> ], [ 26, 4, 2, <identity ...> ], [ 41, 26, 2, \
```
causes the below error.
Replacing this by
```gap
 1, <identity ...> ], [ 25, 1, 1, <identity ...> ], [ 41, 25, 1, <identity ...>\
 ], [ 4, 41, 2, <identity ...> ], [ 26, 4, 2, <identity ...> ], [ 41, 26, 2, \
```
solves this.
This can certainly work as a hotfix, but we should understand why this does not happen when testing via Github Actions and improve the tests to not be susceptible.

**To Reproduce**
Run the tests for HyperCells, i.e.,
```bash
$ gap tst/testall.g
```

**Expected behavior**
All tests are successful.

**Actual behavior**
One of the tests fails with the following error:
```gap
########> Diff in ~/.gap/pkg/HyperCells/tst/TGCellGraph.tst:1164
# Input is:
cg2 := ImportTGCellGraph(input, tg);
], [ 4, 41, 2, <identity ...> ], [ 26, 4, 2, <identity ...> ], [ 41, 26, 2, \
# Expected output:
TGCellGraph( TGCell( ProperTriangleGroup(2, 3, 8), [ x^2, y^3, x*y*z, z*y*x*z*\
...
 [ x*y^-1*x^-1*y^-1*(x*y)^5, x*y^-1*x^-1*y^-1*(x*y)^5, 142, 4, 1, g4 ] ] )
# But found:
TGCellGraph( TGCell( ProperTriangleGroup(2, 3, 8), [ x^2, y^3, x*y*z, z*y*x*z*\
...
 [ x*y^-1*x^-1*y^-1*(x*y)^5, x*y^-1*x^-1*y^-1*(x*y)^5, 142, 4, 1, g4 ] ] )
Syntax error: expression expected in stream:2
], [ 4, 41, 2, <identity ...> ], [ 26, 4, 2, <identity ...> ], [ 41, 26, 2, \
^
Syntax error: ; expected in stream:3
```

**Environment**
 - OS: openSUSE Leap (15.5)
 - GAP version: 4.12.2 of 2022-12-18
 - HyperCells version: 0.9.1-beta
 - Other GAP packages loaded: default + kbmag 1.5.10

**Comment by marcelolooser** [comment]
I have reproduced said issue and the hotfix works as intended. Thank you.
